### PR TITLE
Alpine 3.14

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
Meanwhile 3.13 is out

**Comment by xquery** [comment]
thx for letting us know - cadence of curl-docker release matches curl itself

**Comment by eXeDK** [comment]
Any update on this @xquery ?

**Comment by xquery** [comment]
see https://github.com/curl/curl-docker/issues/54 ... starting a new job has blocked my free cycles for a while, should be getting to this by next release (July 21, 2021)

**Comment by eXeDK** [comment]
Any plans to update to Alpine 3.14.2 on the next release @xquery ? I'm happy to create a PR for the alpine part

**Comment by xquery** [comment]
curl docker release  (w updated alpine) will happen *soon* - apologies for the delay

**Comment by eXeDK** [comment]
Sounds awesome @xquery. Have a good one :-)

**Comment by jay** [comment]
Note we have a pending patch release 7.79.1 coming on Wednesday which will include a fix for HTTP response parsing, and an Alpine user has said 7.79.0 is showing the problem, it's possible it may break packaging.

**Pull request closed without merging**
